config/routes.rb
Rails.application.routes.draw do
	root "forecast#index"
	post "/get_forecast", to: "forecast#get_forecast", as: :get_forecast
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/forecast.rb
class Forecast
	attr_accessor :cached, :location_name,
	              :temperature, :feels_like, :minimum, :maximum,
	              :humidity, :cloud_coverage,
	              :sunrise, :sunset

	def formatted_sunrise
		sunrise&.strftime("%l:%M %p")
	end

	def formatted_sunset
		sunset&.strftime("%l:%M %p")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/forecast_controller.rb
class ForecastController < ApplicationController
	# this endpoint shows the weather search form and the weather details
	def index
		zipcode   = zipcode_param[:zipcode]
		@forecast = if zipcode
			ForecastHelper.forecast_for_zipcode zipcode.to_s
		else
			nil
		end

	rescue Faraday::ResourceNotFound => e
		Rails.logger.error "Faraday/OpenWeather Error: #{e.message}"
		flash[:alert] = "Faraday/OpenWeather Error: #{e.message}"
		redirect_to root_path
	end

	# this endpoint is posted to by the form found in the layout application.html.erb
	def get_forecast
		zipcode = LocationHelper.zipcode_for_address(address_param)

		if zipcode.nil?
			flash[:alert] = "Could not find a zipcode for the address '#{address_param}'"
			return redirect_to root_path
		end

		redirect_to root_path(zipcode: zipcode)

	rescue ActionController::ParameterMissing
		flash[:alert] = "Please provide a valid address search query"
		redirect_to root_path
	end

	private

	def address_param
		params.require(:address)
	end

	def zipcode_param
		params.permit(:zipcode) # this is not required because I chose to share the index page between the address search and the forecast
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forecast_helper.rb
# frozen_string_literal: true
require "open_weather"

module ForecastHelper
	API_KEY          = ENV.fetch('OPENWEATHER_API_KEY').freeze
	CACHE_EXPIRATION = 30.minutes.freeze

	# Given a zipcode, fetch the current weather for that location. Searches are cached for 30 minutes by the zipcode.
	# @param [String] zipcode
	# @return [Forecast, nil] Forecast object or nil if the OpenWeather API client fails
	def self.forecast_for_zipcode(zipcode)
		return nil unless zipcode.present?

		cache_id  = "WeatherHelper#forecast_for_zipcode(#{zipcode})"
		is_cached = Rails.cache.exist?(cache_id)

		data = Rails.cache.fetch(cache_id, expires_in: CACHE_EXPIRATION) do
			if (client = weather_client)
				client.current_weather(zip: zipcode)
			else
				nil
			end
		end

		return nil unless data

		# no need to type check the data object because #current_weather guarantees an OpenWeather::Models::City::Weather object unless an error occurred
		Forecast.new.tap do |forecast|
			forecast.cached         = is_cached
			forecast.location_name  = data.name
			forecast.temperature    = data.main.temp
			forecast.feels_like     = data.main.feels_like
			forecast.minimum        = data.main.temp_min
			forecast.maximum        = data.main.temp_max
			forecast.humidity       = data.main.humidity
			forecast.cloud_coverage = data.clouds.all
			forecast.sunrise        = data.sys.sunrise.in_time_zone(Rails.application.config.time_zone)
			forecast.sunset         = data.sys.sunset.in_time_zone(Rails.application.config.time_zone)
		end
	rescue StandardError => e
		# in prod, these errors and ones in LocationHelper are probably sent to Sentry, DataDog, etc
		nil
	end

	# @return [OpenWeather::Client, nil] The OpenWeather client used to fetch forecasts
	def self.weather_client
		OpenWeather::Client.new(api_key: API_KEY, units: "imperial")
	rescue StandardError => e # based on OpenWeather source code, these errors are probably Faraday errors, but just in case I'm wrong I'll catch all
		nil
	end
end

app/helpers/location_helper.rb
# frozen_string_literal: true
require "geocoder"

module LocationHelper
	# Get the zipcode for a given address. No formatting is applied to the given address before querying Geocoder. See config/initializers/geocoder.rb for caching settings.
	# @return [string, nil] The zipcode for the address, or nil if not found.
	def self.zipcode_for_address address
		return nil unless address.present?

		if (data = Geocoder.search(address))
			data.first.postal_code # data is guaranteed to be an array, based on the docs
		else
			nil
		end
	rescue StandardError => e
		nil
	end
end

app/views/forecast/index.html.erb
<% if @forecast %>
  <div class="forecast-container">
    <div class="current-weather">
      <div class="location"><%= @forecast.location_name %></div>
      <div class="temperature"><%= @forecast.temperature.round %>&deg;</div>
      <div class="feels-like">Feels Like: <b><%= @forecast.feels_like.round %>&deg;</b></div>
      <div class="high-low">
        <div class="high">H: <b><%= @forecast.maximum.round %>&deg;</b></div>
        <div class="low">L: <b><%= @forecast.minimum.round %>&deg;</b></div>
      </div>
    </div>

    <div class="current-weather-details">
      <table>
        <tr>
          <td>Humidity</td>
          <td><%= @forecast.humidity %>%</td>
        </tr>
        <tr>
          <td>Cloud Coverage</td>
          <td><%= @forecast.cloud_coverage %>%</td>
        </tr>
        <tr>
          <td>Sunrise</td>
          <td><%= @forecast.formatted_sunrise %></td>
        </tr>
        <tr>
          <td>Sunset</td>
          <td><%= @forecast.formatted_sunset %></td>
        </tr>
      </table>

      <% if @forecast.cached %>
        <div class="alert">♻ Forecast cached</div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= content_for(:title) || "Weather AI" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
  <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

  <link rel="icon" href="/icon.png" type="image/png">
  <link rel="icon" href="/icon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/icon.png">

  <%# Includes all stylesheet files in app/assets/stylesheets %>
  <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>
<main>
  <%= form_with url: get_forecast_path, method: :post, local: true, class: "search-form" do |form| %>
    <%= form.search_field :address, placeholder: 'Search by zip code or street address', class: "search-input" %>
    <%= form.submit "Get Forecast", class: "search-button" %>
  <% end %>
  <% if flash[:alert] %>
    <div class="alert"><%= flash[:alert] %></div>
  <% end %>
  <%= yield %>
</main>
</body>
</html>